feat: add status prop in checkbox, radio, select, slider and toggle
geist-org/react pull request #530
Opened 2021-05-01 08:08 UTC by gepd

## Checklist

- [x] Fix linting errors
- [x] Tests have been added / updated (or snapshots)

## Change information

To make components more consistents, added the `status` prop who allows to show the component with different colors based in a status.
components affected: `checkbox`, `radio`, `select`, `slider` and `toggle`

Will solve https://github.com/geist-org/react/issues/507

2021-05-03 07:33 UTC, unix requested changes
Looks very good! 
There are still some details that will take you some more time, so if you solve them please at me, I need to debug and review them locally and clean up some commits in the meantime

2021-05-03 07:33 UTC, unix commented on components/checkbox/checkbox.icon.tsx
> +const CheckboxIcon: React.FC<Props> = ({ fill, bg, disabled, checked }) => {
`({ fill: propsFill, bg: propsBg ... })`
It is recommended not to use `_`.

2021-05-03 07:33 UTC, unix commented on components/select/select.tsx
> +  status?: NormalTypes
In the `Dot`, `Badge` and other components, Geist is now using `type` to specify the status, can we change the `status` to `type`? Consistent interface with other components.

2021-05-03 07:33 UTC, unix commented on pages/en-us/components/select.mdx
> +  return (
`return` is not necessary.

2021-05-03 17:26 UTC, gepd commented
@unix  all Done!

2021-05-08 19:14 UTC, gepd commented
Hey @unix I was using the modal compontent and I realised that the actions doesn't have the `type` property, I've a commit fixing that, but I've a doubt with the `passive` attribute, I have completely removed it as I think the `type` prop would be enoght, do you agree?

2021-06-05 12:28 UTC, unix approved these changes

2021-06-05 12:50 UTC, merged